export const LABEL_FRAME_HEIGHT_MM = 21.4;
export const SELLER_FIELD_TOP_MM = 17.2;
export const LABEL_FRAME_ROW_LINES_MM = [3.0, 11.7, 14.7, SELLER_FIELD_TOP_MM];
export const SELLER_TEXT_TOP_MM = SELLER_FIELD_TOP_MM + 0.15;
export const SELLER_SECOND_LINE_Y_MM = SELLER_TEXT_TOP_MM + 2.1;
